dist: bionic
language: python
python: 3.7

install:
  - pip install tox
script:
  - tox

stages:
  - name: tox
  - name: publish to test.pypi.org
    if: env(publish) = true AND type = api
    # to publish, go to https://travis-ci.com/Alan-R/ctypesgen/
    # click more options -> trigger build
    # in textbox enter this:
    # env:
    #   publish: true
  - name: verify
    if: env(publish) = true AND type = api

jobs:
  include:
    - stage: tox
      env: TOXENV=py27

    - stage: tox
      env: TOXENV=py37

    - stage: tox
      env: TOXENV=black

    - stage: publish to test.pypi.org
      install:
        - pip install --upgrade setuptools wheel twine
      script:
        - python setup.py sdist bdist_wheel
        - python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

    - stage: verify
      install:
        - pip install --index-url https://test.pypi.org/simple/ --no-deps ctypesgen
      script:
        - python -c 'import ctypesgencore; print(ctypesgencore.VERSION)'
