---
name: Python Black Formatting

on:
  - push
  - pull_request
  - fork

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install black==23.3.0

      - name: Run Black
        run: |
          black --check --diff setup.py run.py ctypesgen/ \
            --exclude='${{ env.EXCLUDE }}'
        env:
          EXCLUDE: ".*tab.py|ctypesgen/parser/cgrammar.py|\
            ctypesgen/parser/lex.py|ctypesgen/parser/yacc.py"
